name: Run Podcast Simulation with Wav2Lip

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-simulation:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # Step 3: Upgrade pip, setuptools, and wheel
    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    # Step 4: Install system dependencies
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential python3-dev ffmpeg espeak-ng

    # Step 5: Install Python dependencies
    - name: Install Python dependencies
      run: |
        pip install librosa
        pip install numpy --only-binary=:all:
        pip install -r requirements.txt

    # Step 6: Clone Wav2Lip Repository
    - name: Clone Wav2Lip
      run: |
        git clone https://github.com/justinjohn0306/Wav2Lip
        cd Wav2Lip
        wget 'https://github.com/justinjohn0306/Wav2Lip/releases/download/models/wav2lip.pth' -O 'checkpoints/wav2lip.pth'
        wget 'https://github.com/justinjohn0306/Wav2Lip/releases/download/models/wav2lip_gan.pth' -O 'checkpoints/wav2lip_gan.pth'
        wget 'https://github.com/justinjohn0306/Wav2Lip/releases/download/models/resnet50.pth' -O 'checkpoints/resnet50.pth'
        wget 'https://github.com/justinjohn0306/Wav2Lip/releases/download/models/mobilenet.pth' -O 'checkpoints/mobilenet.pth'
        pip install https://raw.githubusercontent.com/AwaleSajil/ghc/master/ghc-1.0-py3-none-any.whl
        pip install git+https://github.com/elliottzheng/batch-face.git@master
        pip install ffmpeg-python

    # Step 7: Test Wav2Lip Inference
    - name: Test Wav2Lip Inference
      run: |
        cd Wav2Lip
        python inference.py --checkpoint_path checkpoints/wav2lip_gan.pth \
        --face test_image.jpg --audio test_audio.mp3 --outfile output_talking_head.mp4

    # Step 8: Run your script
    - name: Run podcast simulation
      run: python script_name.py 

    # Step 10: Configure Git
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"

    # Step 11: Commit changes
    - name: Commit changes
      run: |
        git add .
        git commit -m "Update workflow and requirements"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
