name: Run Podcast Simulation with Wav2Lip

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-simulation:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    # Step 3: Upgrade pip, setuptools, and wheel
    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    # Step 4: Install system dependencies
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential python3-dev ffmpeg espeak-ng

    # Step 5: Install Python dependencies
    - name: Install dependencies
      run: |
        pip install numpy --only-binary=:all:
        pip install librosa --only-binary=:all:
        pip install numba llvmlite --only-binary=:all:
        pip install -r requirements.txt

    # Step 6: Install batch_face
    - name: Install batch_face
      run: pip install git+https://github.com/elliottzheng/batch-face.git

    - name: Clone Wav2Lip
      run: |
        git clone https://github.com/justinjohn0306/Wav2Lip
        cd Wav2Lip
        mkdir -p checkpoints
        wget -O checkpoints/mobilenet.pth https://github.com/justinjohn0306/Wav2Lip/releases/download/models/mobilenet.pth
        wget -O checkpoints/wav2lip.pth https://github.com/justinjohn0306/Wav2Lip/releases/download/models/wav2lip.pth
        wget -O checkpoints/wav2lip_gan.pth https://github.com/justinjohn0306/Wav2Lip/releases/download/models/wav2lip_gan.pth
    # Step 9: Run Podcast Simulation
    - name: Run podcast simulation
      run: python script_name.py  # Replace with your actual script name

    # Step 10: Configure Git
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"

    # Step 11: Commit changes
    - name: Commit changes
      run: |
        git add .
        git commit -m "Update workflow and requirements"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
