name: Run Podcast Simulation with Wav2Lip

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-simulation:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    # Step 3: Upgrade pip, setuptools, and wheel
    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    # Step 4: Install system dependencies
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential python3-dev ffmpeg espeak-ng

    # Step 5: Install PyTorch (if required)
    - name: Install PyTorch
      run: |
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

    # Step 6: Install dependencies with precompiled wheels
    - name: Install dependencies
      run: |
        pip install numpy --only-binary=:all:
        pip install -r requirements.txt

    # Step 7: Clone Wav2Lip Repository
    - name: Clone Wav2Lip
      run: |
        git clone https://github.com/justinjohn0306/Wav2Lip
        cd Wav2Lip
        wget 'https://github.com/justinjohn0306/Wav2Lip/releases/download/models/wav2lip.pth' -O 'checkpoints/wav2lip.pth'
        wget 'https://github.com/justinjohn0306/Wav2Lip/releases/download/models/wav2lip_gan.pth' -O 'checkpoints/wav2lip_gan.pth'
        wget 'https://github.com/justinjohn0306/Wav2Lip/releases/download/models/resnet50.pth' -O 'checkpoints/resnet50.pth'
        wget 'https://github.com/justinjohn0306/Wav2Lip/releases/download/models/mobilenet.pth' -O 'checkpoints/mobilenet.pth'
        a = pip install https://raw.githubusercontent.com/AwaleSajil/ghc/master/ghc-1.0-py3-none-any.whl
        pip install git+https://github.com/elliottzheng/batch-face.git@master
        pip install ffmpeg-python mediapipe==0.10.18

    # Step 8: Download Wav2Lip Pretrained Model
    - name: Download Wav2Lip Model
      run: |
        mkdir -p Wav2Lip/checkpoints
        wget -O Wav2Lip/checkpoints/wav2lip_gan.pth https://github.com/justinjohn0306/Wav2Lip/releases/download/models/wav2lip_gan.pth

    # Step 9: Run your script
    - name: Run podcast simulation
      run: python script_name.py  # Replace with your actual script name

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"

    - name: Commit changes
      run: |
        git add .
        git commit -m "Update workflow and requirements"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
